package ro.ubb.lab7.config;

import ro.ubb.lab7.util.PasswordUtil;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Map;

public final class DatabaseInitializer {

    private DatabaseInitializer() {
    }

    public static void initialize() {
        try (Connection connection = Database.getConnection()) {
            connection.setAutoCommit(false);

            createTables(connection);
            seedUsers(connection);
            seedCitiesAndNeighbors(connection);

            connection.commit();
        } catch (SQLException exception) {
            throw new IllegalStateException("Could not initialize the database.", exception);
        }
    }

    private static void createTables(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(30) NOT NULL UNIQUE,
                        password_hash VARCHAR(64) NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS cities (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(80) NOT NULL UNIQUE
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS city_neighbors (
                        city_id BIGINT NOT NULL,
                        neighbor_id BIGINT NOT NULL,
                        PRIMARY KEY (city_id, neighbor_id),
                        CONSTRAINT fk_city_neighbors_city FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE,
                        CONSTRAINT fk_city_neighbors_neighbor FOREIGN KEY (neighbor_id) REFERENCES cities(id) ON DELETE CASCADE
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS routes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_routes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                        CONSTRAINT chk_route_status CHECK (status IN ('ACTIVE', 'COMPLETED'))
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS route_steps (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        route_id BIGINT NOT NULL,
                        step_order INT NOT NULL,
                        city_id BIGINT NOT NULL,
                        selected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_route_steps_route FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE,
                        CONSTRAINT fk_route_steps_city FOREIGN KEY (city_id) REFERENCES cities(id),
                        CONSTRAINT uq_route_step UNIQUE (route_id, step_order)
                    )
                    """);
        }
    }

    private static void seedUsers(Connection connection) throws SQLException {
        if (tableHasRows(connection, "users")) {
            return;
        }

        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO users (username, password_hash) VALUES (?, ?)")) {
            insertUser(statement, "traveler", PasswordUtil.hash("Route123"));
            insertUser(statement, "planner", PasswordUtil.hash("Journey456"));
        }
    }

    private static void insertUser(PreparedStatement statement, String username, String passwordHash) throws SQLException {
        statement.setString(1, username);
        statement.setString(2, passwordHash);
        statement.executeUpdate();
    }

    private static void seedCitiesAndNeighbors(Connection connection) throws SQLException {
        if (tableHasRows(connection, "cities")) {
            return;
        }

        Map<String, Long> cityIds = new LinkedHashMap<>();
        for (String cityName : new String[]{
                "Cluj-Napoca",
                "Oradea",
                "Alba Iulia",
                "Sibiu",
                "Targu Mures",
                "Brasov",
                "Deva",
                "Arad",
                "Timisoara",
                "Bucuresti"
        }) {
            cityIds.put(cityName, insertCity(connection, cityName));
        }

        linkBidirectional(connection, cityIds, "Cluj-Napoca", "Oradea");
        linkBidirectional(connection, cityIds, "Cluj-Napoca", "Alba Iulia");
        linkBidirectional(connection, cityIds, "Cluj-Napoca", "Targu Mures");
        linkBidirectional(connection, cityIds, "Oradea", "Arad");
        linkBidirectional(connection, cityIds, "Alba Iulia", "Sibiu");
        linkBidirectional(connection, cityIds, "Alba Iulia", "Deva");
        linkBidirectional(connection, cityIds, "Targu Mures", "Sibiu");
        linkBidirectional(connection, cityIds, "Targu Mures", "Brasov");
        linkBidirectional(connection, cityIds, "Sibiu", "Brasov");
        linkBidirectional(connection, cityIds, "Sibiu", "Deva");
        linkBidirectional(connection, cityIds, "Brasov", "Bucuresti");
        linkBidirectional(connection, cityIds, "Deva", "Arad");
        linkBidirectional(connection, cityIds, "Deva", "Timisoara");
        linkBidirectional(connection, cityIds, "Arad", "Timisoara");
    }

    private static long insertCity(Connection connection, String cityName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO cities (name) VALUES (?)",
                Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, cityName);
            statement.executeUpdate();

            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getLong(1);
                }
            }
        }

        throw new SQLException("Could not insert city " + cityName);
    }

    private static void linkBidirectional(Connection connection, Map<String, Long> cityIds, String from, String to) throws SQLException {
        insertNeighbor(connection, cityIds.get(from), cityIds.get(to));
        insertNeighbor(connection, cityIds.get(to), cityIds.get(from));
    }

    private static void insertNeighbor(Connection connection, long cityId, long neighborId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO city_neighbors (city_id, neighbor_id) VALUES (?, ?)")) {
            statement.setLong(1, cityId);
            statement.setLong(2, neighborId);
            statement.executeUpdate();
        }
    }

    private static boolean tableHasRows(Connection connection, String tableName) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) FROM " + tableName)) {
            resultSet.next();
            return resultSet.getInt(1) > 0;
        }
    }
}
